--ASSIGNMENT 2--

//CREATE 2 TABLES
CREATE TABLE JOB (
    JOB_CODE CHAR(3) CONSTRAINT JOB_PK PRIMARY KEY,
    JOB_CLASS CHAR(30),
    CHG_HOUR NUMBER(5,2));
    
CREATE TABLE EMP11 (
    EMP_NUM NUMBER (*,5) CONSTRAINT EMP_PK PRIMARY KEY,
    EMP_FNAME CHAR(20),
    EMP_LNAME CHAR(20) CONSTRAINT EMP_LNAME_UK UNIQUE NOT NULL,
    JOB_CLASS CHAR(3) CONSTRAINT JOB_FK REFERENCES JOB(JOB_CODE),
    HIREDATE DATE NOT NULL);
    
//INSERT 5 RECORDS IN EACH TABLES
--TABLE JOB RECORDS--
INSERT INTO JOB (JOB_CODE, JOB_CLASS, CHG_HOUR) VALUES ('E01', 'HR JOB CLASS', 10.00);
INSERT INTO JOB (JOB_CODE, JOB_CLASS, CHG_HOUR) VALUES ('E02', 'HR JOB CLASS', 20.00);
INSERT INTO JOB (JOB_CODE, JOB_CLASS, CHG_HOUR) VALUES ('E03', 'HR JOB CLASS', 30.00);
INSERT INTO JOB (JOB_CODE, JOB_CLASS, CHG_HOUR) VALUES ('E04', 'HR JOB CLASS', 40.00);
INSERT INTO JOB (JOB_CODE, JOB_CLASS, CHG_HOUR) VALUES ('E05', 'HR JOB CLASS', 50.00);

 SELECT * FROM JOB;
 
 SELECT * FROM EMP11;

--TABLE EMP11 RECORDS--
INSERT INTO EMP11 (EMP_NUM, EMP_FNAME, EMP_LNAME, JOB_CLASS, HIREDATE) VALUES (01,'JENNY', 'DAI', 'E01', '2019-05-12');
INSERT INTO EMP11 (EMP_NUM, EMP_FNAME, EMP_LNAME, JOB_CLASS, HIREDATE) VALUES (02,'SAMM', 'JONAS', 'E02', '2018-05-12');
INSERT INTO EMP11 (EMP_NUM, EMP_FNAME, EMP_LNAME, JOB_CLASS, HIREDATE) VALUES (03,'JANE', 'OBBASAI', 'E03', '2019-05-12');
INSERT INTO EMP11 (EMP_NUM, EMP_FNAME, EMP_LNAME, JOB_CLASS, HIREDATE) VALUES (04,'SOTHYRA', 'CHAN', 'E04', '2018-05-12');
INSERT INTO EMP11 (EMP_NUM, EMP_FNAME, EMP_LNAME, JOB_CLASS, HIREDATE) VALUES (05,'PANHA', 'SETH', 'E05', '2019-05-12');


//Q1
--a. Add a column named overtimeCharge (NOT NULL)
ALTER TABLE JOB
ADD overtimeCharge NUMBER NOT NULL;

--b. Add constraint named charge_ck (CHG_HOUR >=25)
ALTER TABLE JOB
ADD CONSTRAINT charge_ck CHECK (CHG_HOUR >=25);

//Q2
--Delete constraint name charge_ck--
ALTER Table JOB
DROP CONSTRAINT charge_ck;

//Q3
--Delete overtimeCharge column--
ALTER TABLE JOB
DROP COLUMN overtimeCharge;


//Q4
--Create new table containing two columns from the existing EMP11 table--
CREATE TABLE EMP11_master AS
SELECT EMP_NUM, EMP_FNAME, EMP_LNAME 
FROM EMP11;

Select * FROM EMP11_master;

--Rename a column--
ALTER TABLE EMP11_master
RENAME COLUMN EMP_NUM to EMP_ID;

--Add a new column--
ALTER TABLE EMP11_master
ADD EMP_birthdate DATE;


//Q5
--Delete the EMP11_MASTER Table permanently so its not moved to recycle bin--
DROP TABLE EMP11_master PURGE;

--Delete the EMP11 table so it can be restored later--
--Open the recycle bin first--
ALTER SESSION SET RECYCLEBIN='ON';

DROP TABLE EMP11;

--Restore the table back--
FLASHBACK TABLE EMP11 TO BEFORE DROP;

SELECT * FROM EMP11;


